// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhhasvvaspuzomelwflk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoaGFzdnZhc3B1em9tZWx3ZmxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MjE3NjQsImV4cCI6MjA3MjA5Nzc2NH0.OUjNnseUwghAztmDLtInBM_Gi7R1GZg8JAJmPF9l5qw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});